### PR TITLE
feat: Startup detail pages

### PR DESCRIPTION
**Pull request by lankabelgezogen**
Venture has to input their own data, required structure can be found in data/e-lab-startups.json

Example detail page can be found at:
http://localhost:3000/e-lab/startups/airbnb

An overview of the startups can also be embedded like this in e-lab/page.tsx:

```tsx
<Section className="bg-purple-950 text-white">
  <h2 className="mb-12 bg-gradient-to-r from-yellow-500 to-red-500 bg-clip-text text-center text-3xl font-semibold uppercase tracking-widest text-transparent sm:text-5xl">
    Our Startups
  </h2>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    {startups.map((startup) => (
      <Link
        key={startup.id}
        href={`/e-lab/startups/${startup.id}`}
        className="bg-purple-900 p-6 rounded-lg hover:bg-purple-800 transition-colors"
      >
        <h3 className="text-2xl font-semibold mb-2">{startup.name}</h3>
        <p className="text-gray-300">{startup.description}</p>
      </Link>
    ))}
  </div>
</Section>
```

### CODE REVIEW

**Review by simon-hng — APPROVED** [review]
Code LGTM

**Comment by LaurenzSommerlad** [comment]
Draft looks great but needs more padding at the top. We could add integration with my new people component once merged to link to founders pages & add social links to contact them

**Comment by Cyro292** [comment]
image
There is some weird bug for 1s when trying to find a startup that dosen't exist. I will try to fix that

**Review by LaurenzSommerlad — CHANGES_REQUESTED** [review]
Todos: a few of our startups need to be added before merge into dev as we currently deploy from branch develop. Coding standards of course 😁🫠😅

Furthermore, more design changes and features pending by @zausin33

**Comment by Cyro292** [comment]
https://github.com/tum-ai/website/pull/112#issuecomment-2228657688

Adress this here.

**Comment by sofiiadan** [comment]
Not sure it is an up-to-date branch, so no approval yet.

**Review by sofiiadan — CHANGES_REQUESTED** [review]
The branch does not seem to be up-to-date, so not approval, possibly (if the changes are applied elsewhere) we can close it?

**Pull request closed without merging**
