### PR TITLE
feat: startup-list

### PR DESCRIPTION
**Pull request by zausin33**
Filterable and searchable list of startups added below the timeline section.
image

Mobile View:
image
image

With linking to startup detail page.
image

### CODE REVIEW

**Comment by LaurenzSommerlad** [comment]
Absolutely love how this is turning out. Would like to add similar info cards like y combinator directory has for company socials and founders. Feel free to use my design from the team page pr as starting point.

**Comment by LaurenzSommerlad** [comment]
A tab for open positions for each company and culminated on the directory page, in other words, being able to search for open positions is definitely also a cool feature that a few startups have shown interest in 👀😁

**Comment by LaurenzSommerlad** [comment]
Super minor thing, button color for filter could be either TUM.ai violet or orange-500 or so to be in the middle of the color transition (yellow-red)

**Comment by zausin33** [comment]
> Absolutely love how this is turning out. Would like to add similar info cards like y combinator directory has for company socials and founders. Feel free to use my design from the team page pr as starting point.
> 
> 

This only concerns the startup detail page, right? Then this would belong to the other pull request.

**Comment by zausin33** [comment]
> A tab for open positions for each company and culminated on the directory page, in other words, being able to search for open positions is definitely also a cool feature that a few startups have shown interest in 👀😁

Could you give us an example how this should look like on the directory page / startup list. Also similar to the tags we already added or somehow different?

**Comment by LaurenzSommerlad** [comment]
@zausin33 there are definitely a lot of different ways but for better oversight I would start thinking about a second nav bar. 
We currently have e-lab page, startups, team and open jobs. That's already a lot for a single page, so I would suggest divide and conquer haha

I like the added filter for is hiring including the integration of startup positions in each company next to a news sub page for the respective company where we could add fundraising rounds and so on. (Ref Y Combinator foto from earlier)

Additionally I wouldn't add these jobs to the startup directory directly and rather add them as separate open jobs/ startup jobs directory on a separate sub page with filters like, sales, engineering, design, project management, marketing, founders associate, ect.

Feel free to be inspired by y comb and other incubators




Ps. Don't forget to pull new changes from team page before merge conflicts arise 👀

**Comment by Cyro292** [comment]
> Absolutely love how this is turning out. Would like to add similar info cards like y combinator directory has for company socials and founders. Feel free to use my design from the team page pr as starting point.
> 
> 

Indeed, this is an issue related to the Startup Detail Page. I will address it there.

**Comment by Cyro292** [comment]
> A tab for open positions for each company and culminated on the directory page, in other words, being able to search for open positions is definitely also a cool feature that a few startups have shown interest in 👀😁

Let’s separate these concerns into another pull request and ticket. For now, let’s focus on getting this startup list done first.
Btw. great input, Laurenz.

**Review by Cyro292 — APPROVED** [review]
LGTM

**Comment by Cyro292** [comment]
Some things are missing regarding Data used in the Ticket. Therefore we wait on the data beeing exchanged.

**Pull request merged**
