### PR TITLE
feat: full-startup-page

### PR DESCRIPTION
**Pull request by Cyro292**
as the data was not yet corretly inserted here we reverted the merge and needed to create a new pull request. This will be merged when the new data is inserted.

### CODE REVIEW

**Comment by Cyro292** [comment]
https://github.com/tum-ai/website/pull/112

**Review by lankabelgezogen — APPROVED** [review]
LGTM

**Review by LaurenzSommerlad — CHANGES_REQUESTED** [review]
Please only merge once data is added

**Comment by Cyro292** [comment]
Feature now moved to a separate page. You can find the latest commits in Startuplist.

**Pull request closed without merging**
