### PR TITLE
refactor: partners

### PR DESCRIPTION
**Pull request by Max-vS**

### CODE REVIEW

**Comment by simon-hng** [comment]
`npm run format`

**Review by simon-hng — COMMENTED** [review]
Code and preview deployment LGTM.

I asked `Marina Momina` to test the changes as well so once she is done you can merge

**Comment by marinamomina** [comment]
Bugs / stuff to fix:
1. Imprint misspelled
imprint
2.Maybe we should pick another word for enablers, it also has a negative meaning
enabler1
enabler2
3. Should we add more space here?
image
4. I think we should elaborate a bit on every role a sponsor can take and what for example challenge setter means, but better to check with PnS
image
5. "With a specialization in AI" sounds weird, maybe reformulate 
image
like experienced in Machine Learning pipe lines, advanced data analysis, applying ML decisions to business use cases, so it sound more business, I would talk to PnS and ask them if they proof read texts
6. I would change the text, so it will sound more professional 
image
7. "Our" repeated 3 times, I would reformulate this text
image
8. Resolution of logos especially TUM.ai one is low
image
9. I would change the phrasing or add an article like "a change"
image

**Comment by simon-hng** [comment]
Thanks for the review @marinamomina .

I will move the issues into separate tickets in linear as this is out of scope for this pr

**Review by simon-hng — APPROVED** [review]

**Pull request merged**
